version: "3"

services:
  mistralmail:
    build: 
      context: .
    container_name: mistralmail
    environment:
      - HOSTNAME
      - SMTP_OUTGOING_MODE=RELAY
      - EXTERNAL_RELAY_HOSTNAME
      - EXTERNAL_RELAY_PORT
      - EXTERNAL_RELAY_USERNAME
      - EXTERNAL_RELAY_PASSWORD
      - EXTERNAL_RELAY_INSECURE_SKIP_VERIFY
      - TLS_ACME_EMAIL
      - TLS_ACME_ENDPOINT
      - TLS_ACME_CHALLENGE
      - TLS_ACME_DNS_PROVIDER
      - SECRET
      - SENTRY_DSN
      - LOG_FULL_QUERIES
      - SPAM_CHECK_ENABLE
      - LEGO_CA_CERTIFICATES
    ports:
      - "25:25"
      - "587:587"
      - "143:143"
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./certificates:/mistralmail/certificates

  pebble:
    # for testing ACME challenges
    image: letsencrypt/pebble
    ports:
      - 14000:14000  # ACME port
      - 15000:15000  # Management port
    environment:
      - PEBBLE_VA_NOSLEEP=1