version: "3"

services:
  gopistolet:
    build: 
      context: .
    container_name: gopistolet
    environment:
      - SMTP_OUTGOING_MODE=RELAY
      - EXTERNAL_RELAY_HOSTNAME=${EXTERNAL_RELAY_HOSTNAME}
      - EXTERNAL_RELAY_PORT=${EXTERNAL_RELAY_PORT}
      - EXTERNAL_RELAY_INSECURE_SKIP_VERIFY=true
    ports:
      - "25:25"
      - "587:587"
      - "143:143"

  pebble:
    # for testing ACME challenges
    image: letsencrypt/pebble
    ports:
      - 14000:14000  # ACME port
      - 15000:15000  # Management port
    environment:
      - PEBBLE_VA_NOSLEEP=1